# WWW
[[redirects]]
from = "/www.hirechrisfinazzo.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "/https://gracious-babbage-21fe68.netlify.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
# Plugins
[[plugins]]
package = "netlify-plugin-csp-generator"
  [plugins.inputs]
  buildDir = "build"
  reportURI = "https://chrisfinazzo.report-uri.com/r/d/csp/reportOnly"
  reportTo = "csp-violation-reporter"
  reportOnly = true
  [plugins.inputs.policies]
    defaultSrc = "'self'"
    fontSrc = "'self'"
    imgSrc = "'https:'"
    styleSrc = "'self' 'https://use.fontawesome.com'"
    scriptSrc = "'self'"
    connectSrc = "'self'"
    formAction = "'https://formspree.io/f/xgerekvv'"
    frameAncestors = "'none'"
    workerSrc = "'self'"

[[headers]]
  for = "/*"
  [headers.values]  
    cache-control = '''
    max-age=0,
    public,
    must-revalidate,
    no-transform'''
    Reporting-Endpoints = "https://chrisfinazzo.report-uri.com/r/d/csp/reportOnly"
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

