# WWW
[[redirects]]
from = "/www.hirechrisfinazzo.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Netlify
[[redirects]]
from = "/https://gracious-babbage-21fe68.netlify.com"
to = "/hirechrisfinazzo.com"
status = 301
force = false
# Routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false

[[headers]]
  for = "/*"

  [headers.values]  
    Cache-Control = "no-transform"
    Content-Security-Policy-Report-Only = '''
    default-src 'self';
    font-src 'self' https://fonts.gstatic.com https://use.fontawesome.com;
    img-src https:;
    object-src 'none';
    script-src 'self';
    style-src 'self' https://fonts.googleapis.com https://use.fontawesome.com;
    worker-src 'self';
    base-uri 'self';
    manifest-src 'self';
    connect-src 'self';
    form-action https://formspree.io/chris@chrisfinazzo.com;
    frame-ancestors 'none';
    report-uri https://5e6ec6f0ebe3841854b1d94c.endpoint.csper.io; '''
    Upgrade-Insecure-Requests = "1"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
